project:
  type: book
  output-dir: docs

book:
  title: "A Thesis Submitted for a PhD degree at ASU"
  author: "John Doe"
  date: today
  description: "A thesis submitted for the degree of Doctor of Philosophy at Arizona State University in 2023. Ira A. Fulton Schools of Engineering"
  chapters: # include index and all chapters except chapter 1
    - index.qmd # this is chapter 1
    - "02-chap2.qmd"
  appendices:
    - "A-appA.qmd"
    - "A-appB.qmd"
  references: "10-refs.qmd"
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. ©2023, John Doe"
    border: false
    background: light
  downloads: [pdf, epub] # optional

thesis:
  doctype: Dissertation # Choose from Dissertation, Report, Thesis
  degreetype: Doctor of Philosophy # Choose from Doctor of Philosophy, Master of Engineering, Mater of Science, Bachelor of Science etc.
  defdate: July 2023 # Give month (written out fully) and year of the oral defense
  gradmonth: May # Choose from May, August or December 
  gradyear: 2023
  committeechair: 
    - Jane Smith
  committeemember:
    - Joe Bloggs
    - So-and-so
  keywords: # up to six
    - lorem
    - ipsum
  copyright: true # optional
  frontmatter:
    abstract: "00-abstract.tex"
    dedication: "00-dedication.tex"
    acknowledgments: "00-acknowledgements.tex"
  backmatter:
    biosketch: "99-biosketch.tex"

bibliography: 99-thesisrefs.bib

format:
  asu-thesis-pdf:
    keep-tex: false
    pdf-engine: pdflatex
  asu-thesis-html: default
  epub: default # optional
execute:
  freeze: auto
  echo: false
  warning: false
  error: false


