project:
  type: book

book:
  title: "A Thesis Submitted for a PhD degree at ASU"
  author: "John Doe"
  description: "A thesis submitted for the degree of Doctor of Philosophy at Arizona State University in 2023. Ira A. Fulton Schools of Engineering"
  chapters: # include index and all chapters except chapter 1
    - index.qmd # this is chapter 1
    - "./chapters/02-chap2.qmd" 
  appendices:
    - "./appendices/A-appA.qmd"
  references: "./backmatter/refs.qmd"
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023, John Doe Su"
    border: false
    background: light
  sidebar:
    background: "#8C1D40"
    style: "docked"

thesis:
  doctype: Dissertation # Choose from Dissertation, Report, Thesis
  degreetype: Doctor of Philosophy # Choose from Doctor of Philosophy, Master of Engineering, Mater of Science, Bachelor of Science etc.
  defdate: July 2023 # Give month (written out fully) and year of the oral defense
  gradmonth: May # Choose from May, August or December 
  gradyear: 2023
  committeechair: Jane Smith
  committeemember:
    - Joe Bloggs
    - So-and-so
  keywords: # up to six
    - lorem
    - ipsum
  frontmatter:
    abstract: "./frontmatter/abstract.tex"
    dedication: "./frontmatter/dedication.tex"
    acknowledgments: "./frontmatter/acknowledgements.tex"
  backmatter:
    biosketch: "./backmatter/biosketch.tex"

published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: thesisrefs.bib
# suppress-bibliography: true

format:
  asudis-pdf:
    keep-tex: true

execute:
  freeze: auto
  echo: false
  warning: false
  error: false


